/**
 * Hull Presets - Comprehensive library of hull designs users can select and modify
 */

import { ProceduralHullConfig, ControlPoint } from './HullTypes'
import type { HullPreset } from './HullTypes'

// Re-export HullPreset type for convenience
export type { HullPreset }

// Default waterline profile (teardrop shape)
const defaultWaterlineProfile: ControlPoint[] = [
  { x: -1, y: 0, handleOut: { x: -0.9, y: 0.3 } },
  { x: -0.5, y: 0.4, handleIn: { x: -0.7, y: 0.4 }, handleOut: { x: -0.3, y: 0.4 } },
  { x: 0, y: 0.5, handleIn: { x: -0.2, y: 0.5 }, handleOut: { x: 0.2, y: 0.5 } },
  { x: 0.5, y: 0.4, handleIn: { x: 0.3, y: 0.4 }, handleOut: { x: 0.7, y: 0.3 } },
  { x: 1, y: 0 },
]

// Default buttock profile (side view)
const defaultButtockProfile: ControlPoint[] = [
  { x: -1, y: 0.2, handleOut: { x: -0.8, y: 0.1 } },
  { x: -0.3, y: 0, handleIn: { x: -0.5, y: 0 }, handleOut: { x: 0, y: 0 } },
  { x: 0.5, y: 0.1, handleIn: { x: 0.2, y: 0 }, handleOut: { x: 0.7, y: 0.15 } },
  { x: 1, y: 0.3 },
]

// Create default hull config base
const createDefaultConfig = (): ProceduralHullConfig => ({
  length: 12,
  beam: 4,
  draft: 0.8,
  freeboard: 1.0,
  category: 'monohull',
  bow: {
    type: 'piercing',
    angle: 25,
    overhang: 10,
    flare: 10,
    rake: 15,
    bulbSize: 0,
    bulbPosition: 0.5,
  },
  stern: {
    type: 'transom',
    angle: 15,
    overhang: 5,
    width: 0.8,
    height: 0.6,
    rake: 10,
  },
  keel: {
    type: 'v-hull',
    depth: 0.3,
    length: 0.6,
    position: 0.5,
    sweep: 15,
    finType: 'none',
    finDepth: 0,
  },
  chine: {
    type: 'soft',
    count: 1,
    positions: [0.3],
    angles: [15],
  },
  deck: {
    camber: 3,
    sheer: 0.2,
    coachRoof: true,
    coachRoofHeight: 0.6,
    coachRoofLength: 0.35,
    flybridge: false,
  },
  rocker: {
    bowRise: 0.15,
    sternRise: 0.08,
    centerPoint: 0.45,
    continuous: true,
  },
  crossSections: [],
  waterlineProfile: defaultWaterlineProfile,
  buttockProfile: defaultButtockProfile,
  prismaticCoefficient: 0.55,
  blockCoefficient: 0.45,
  midshipCoefficient: 0.75,
  wettedSurfaceArea: 0,
  displacement: 0,
  colors: {
    hull: '#F8FAFC',
    deck: '#1E293B',
    accent: '#06B6D4',
    antifoul: '#0F172A',
  },
  material: 'fiberglass',
  finish: 'gloss',
})

// ============================================================
// HULL PRESETS LIBRARY
// ============================================================

export const HULL_PRESETS: HullPreset[] = [
  // --- RACING CATEGORY ---
  {
    id: 'racing-foiler',
    name: 'Racing Foiler',
    description: 'Ultra-light racing hull designed for hydrofoil integration. Minimal wetted surface, aggressive entry.',
    category: 'racing',
    icon: '🏎️',
    unlockCost: 5000,
    performanceRating: {
      speed: 10,
      stability: 4,
      comfort: 2,
      efficiency: 9,
      seakeeping: 3,
    },
    config: {
      length: 15,
      beam: 3.5,
      draft: 0.5,
      freeboard: 0.8,
      bow: {
        type: 'wave-piercing',
        angle: 12,
        overhang: 5,
        flare: 5,
        rake: 25,
        bulbSize: 0,
        bulbPosition: 0.5,
      },
      stern: {
        type: 'reverse-transom',
        angle: -5,
        overhang: 0,
        width: 0.6,
        height: 0.4,
        rake: 5,
      },
      keel: {
        type: 'flat',
        depth: 0.15,
        length: 0.8,
        position: 0.5,
        sweep: 0,
        finType: 'wing',
        finDepth: 1.5,
      },
      prismaticCoefficient: 0.52,
      blockCoefficient: 0.35,
      material: 'carbon',
    },
  },
  {
    id: 'ocean-racer',
    name: 'Ocean Racer',
    description: 'Offshore racing design with deep V hull for rough water performance. Fast and powerful.',
    category: 'racing',
    icon: '⚡',
    unlockCost: 3500,
    performanceRating: {
      speed: 9,
      stability: 6,
      comfort: 4,
      efficiency: 7,
      seakeeping: 8,
    },
    config: {
      length: 14,
      beam: 4.2,
      draft: 1.2,
      freeboard: 1.1,
      bow: {
        type: 'piercing',
        angle: 18,
        overhang: 15,
        flare: 15,
        rake: 20,
        bulbSize: 0,
        bulbPosition: 0.5,
      },
      stern: {
        type: 'transom',
        angle: 12,
        overhang: 8,
        width: 0.85,
        height: 0.5,
        rake: 8,
      },
      keel: {
        type: 'deep-v',
        depth: 0.6,
        length: 0.7,
        position: 0.48,
        sweep: 25,
        finType: 'bulb',
        finDepth: 2.5,
      },
      prismaticCoefficient: 0.56,
      blockCoefficient: 0.42,
      material: 'carbon',
    },
  },
  {
    id: 'daysailer',
    name: 'Daysailer Sprint',
    description: 'Nimble single-handed racer for coastal waters. Quick tacking and responsive.',
    category: 'racing',
    icon: '🌊',
    unlockCost: 1500,
    performanceRating: {
      speed: 7,
      stability: 6,
      comfort: 5,
      efficiency: 8,
      seakeeping: 5,
    },
    config: {
      length: 9,
      beam: 2.8,
      draft: 0.6,
      freeboard: 0.7,
      bow: {
        type: 'flared',
        angle: 22,
        overhang: 12,
        flare: 18,
        rake: 18,
        bulbSize: 0,
        bulbPosition: 0.5,
      },
      stern: {
        type: 'transom',
        angle: 10,
        overhang: 5,
        width: 0.75,
        height: 0.5,
        rake: 5,
      },
      keel: {
        type: 'v-hull',
        depth: 0.3,
        length: 0.65,
        position: 0.5,
        sweep: 20,
        finType: 'daggerboard',
        finDepth: 1.8,
      },
    },
  },

  // --- CRUISING CATEGORY ---
  {
    id: 'coastal-cruiser',
    name: 'Coastal Cruiser',
    description: 'Comfortable weekend cruiser with good stability and moderate performance. Perfect starter yacht.',
    category: 'cruising',
    icon: '⛵',
    unlockCost: 0, // Starter
    performanceRating: {
      speed: 5,
      stability: 8,
      comfort: 8,
      efficiency: 6,
      seakeeping: 6,
    },
    config: {
      length: 12,
      beam: 4,
      draft: 0.8,
      freeboard: 1.0,
      bow: {
        type: 'flared',
        angle: 28,
        overhang: 12,
        flare: 20,
        rake: 15,
        bulbSize: 0,
        bulbPosition: 0.5,
      },
      stern: {
        type: 'sugar-scoop',
        angle: 20,
        overhang: 10,
        width: 0.9,
        height: 0.65,
        rake: 12,
      },
      keel: {
        type: 'modified-v',
        depth: 0.4,
        length: 0.6,
        position: 0.5,
        sweep: 18,
        finType: 'stub',
        finDepth: 0.8,
      },
      deck: {
        camber: 4,
        sheer: 0.25,
        coachRoof: true,
        coachRoofHeight: 0.7,
        coachRoofLength: 0.4,
        flybridge: false,
      },
    },
  },
  {
    id: 'bluewater-cruiser',
    name: 'Bluewater Voyager',
    description: 'Heavy displacement hull for ocean passages. Maximum comfort and safety for long journeys.',
    category: 'cruising',
    icon: '🌍',
    unlockCost: 4000,
    performanceRating: {
      speed: 4,
      stability: 10,
      comfort: 9,
      efficiency: 5,
      seakeeping: 10,
    },
    config: {
      length: 16,
      beam: 4.8,
      draft: 1.8,
      freeboard: 1.3,
      bow: {
        type: 'clipper',
        angle: 32,
        overhang: 18,
        flare: 15,
        rake: 12,
        bulbSize: 0,
        bulbPosition: 0.5,
      },
      stern: {
        type: 'canoe',
        angle: 25,
        overhang: 15,
        width: 0.7,
        height: 0.7,
        rake: 15,
      },
      keel: {
        type: 'deep-v',
        depth: 0.8,
        length: 0.55,
        position: 0.52,
        sweep: 20,
        finType: 'bulb',
        finDepth: 2.2,
      },
      rocker: {
        bowRise: 0.2,
        sternRise: 0.12,
        centerPoint: 0.48,
        continuous: true,
      },
      prismaticCoefficient: 0.58,
      blockCoefficient: 0.48,
      material: 'fiberglass',
    },
  },
  {
    id: 'motor-sailer',
    name: 'Motor Sailer',
    description: 'Hybrid hull optimized for both sail and motor. Efficient under power with sailing capability.',
    category: 'cruising',
    icon: '🚢',
    unlockCost: 2500,
    performanceRating: {
      speed: 6,
      stability: 9,
      comfort: 8,
      efficiency: 7,
      seakeeping: 7,
    },
    config: {
      length: 14,
      beam: 4.5,
      draft: 1.0,
      freeboard: 1.2,
      bow: {
        type: 'bulbous',
        angle: 30,
        overhang: 8,
        flare: 12,
        rake: 10,
        bulbSize: 0.25,
        bulbPosition: 0.4,
      },
      stern: {
        type: 'cruiser',
        angle: 18,
        overhang: 12,
        width: 0.85,
        height: 0.6,
        rake: 10,
      },
      keel: {
        type: 'modified-v',
        depth: 0.5,
        length: 0.65,
        position: 0.5,
        sweep: 15,
        finType: 'stub',
        finDepth: 1.0,
      },
      deck: {
        camber: 3,
        sheer: 0.2,
        coachRoof: true,
        coachRoofHeight: 0.8,
        coachRoofLength: 0.45,
        flybridge: true,
      },
    },
  },

  // --- EXPEDITION CATEGORY ---
  {
    id: 'explorer-vessel',
    name: 'Explorer Vessel',
    description: 'Heavy-duty expedition hull for remote destinations. Ice-strengthened design with high freeboard.',
    category: 'expedition',
    icon: '🧭',
    unlockCost: 6000,
    performanceRating: {
      speed: 4,
      stability: 10,
      comfort: 7,
      efficiency: 5,
      seakeeping: 10,
    },
    config: {
      length: 18,
      beam: 5.5,
      draft: 1.5,
      freeboard: 1.6,
      bow: {
        type: 'axe',
        angle: 35,
        overhang: 5,
        flare: 8,
        rake: 8,
        bulbSize: 0,
        bulbPosition: 0.5,
      },
      stern: {
        type: 'transom',
        angle: 15,
        overhang: 5,
        width: 0.9,
        height: 0.7,
        rake: 8,
      },
      keel: {
        type: 'round-bottom',
        depth: 0.7,
        length: 0.7,
        position: 0.52,
        sweep: 10,
        finType: 'stub',
        finDepth: 0.5,
      },
      chine: {
        type: 'hard',
        count: 2,
        positions: [0.25, 0.5],
        angles: [12, 8],
      },
      material: 'aluminum',
      prismaticCoefficient: 0.62,
      blockCoefficient: 0.52,
    },
  },
  {
    id: 'pocket-explorer',
    name: 'Pocket Explorer',
    description: 'Compact expedition hull for solo adventurers. Efficient and seaworthy for its size.',
    category: 'expedition',
    icon: '⛰️',
    unlockCost: 2000,
    performanceRating: {
      speed: 5,
      stability: 8,
      comfort: 6,
      efficiency: 8,
      seakeeping: 8,
    },
    config: {
      length: 10,
      beam: 3.2,
      draft: 1.0,
      freeboard: 0.9,
      bow: {
        type: 'plumb',
        angle: 30,
        overhang: 2,
        flare: 10,
        rake: 3,
        bulbSize: 0,
        bulbPosition: 0.5,
      },
      stern: {
        type: 'double-ended',
        angle: 22,
        overhang: 8,
        width: 0.5,
        height: 0.6,
        rake: 12,
      },
      keel: {
        type: 'modified-v',
        depth: 0.5,
        length: 0.6,
        position: 0.5,
        sweep: 18,
        finType: 'centerboard',
        finDepth: 1.5,
      },
    },
  },

  // --- LUXURY CATEGORY ---
  {
    id: 'superyacht-tender',
    name: 'Superyacht Tender',
    description: 'Sleek luxury tender with planing hull. Fast, stylish, and comfortable.',
    category: 'luxury',
    icon: '💎',
    unlockCost: 4500,
    performanceRating: {
      speed: 8,
      stability: 6,
      comfort: 9,
      efficiency: 5,
      seakeeping: 5,
    },
    config: {
      length: 8,
      beam: 2.8,
      draft: 0.4,
      freeboard: 0.6,
      bow: {
        type: 'flared',
        angle: 20,
        overhang: 15,
        flare: 25,
        rake: 22,
        bulbSize: 0,
        bulbPosition: 0.5,
      },
      stern: {
        type: 'ducktail',
        angle: 5,
        overhang: 8,
        width: 0.95,
        height: 0.4,
        rake: 3,
      },
      keel: {
        type: 'deep-v',
        depth: 0.25,
        length: 0.75,
        position: 0.55,
        sweep: 0,
        finType: 'none',
        finDepth: 0,
      },
      chine: {
        type: 'spray-rail',
        count: 3,
        positions: [0.2, 0.4, 0.6],
        angles: [20, 15, 10],
      },
      finish: 'metallic',
      colors: {
        hull: '#1E293B',
        deck: '#F8FAFC',
        accent: '#D4A574',
        antifoul: '#0F172A',
      },
    },
  },
  {
    id: 'electric-dayboat',
    name: 'Electric Dayboat',
    description: 'Modern electric-optimized hull. Silent cruising with solar integration surfaces.',
    category: 'luxury',
    icon: '🔋',
    unlockCost: 3000,
    performanceRating: {
      speed: 6,
      stability: 8,
      comfort: 9,
      efficiency: 10,
      seakeeping: 6,
    },
    config: {
      length: 11,
      beam: 3.6,
      draft: 0.5,
      freeboard: 0.8,
      bow: {
        type: 'wave-piercing',
        angle: 18,
        overhang: 10,
        flare: 12,
        rake: 18,
        bulbSize: 0,
        bulbPosition: 0.5,
      },
      stern: {
        type: 'sugar-scoop',
        angle: 12,
        overhang: 12,
        width: 0.9,
        height: 0.5,
        rake: 8,
      },
      keel: {
        type: 'tunnel',
        depth: 0.2,
        length: 0.5,
        position: 0.6,
        sweep: 0,
        finType: 'none',
        finDepth: 0,
      },
      deck: {
        camber: 2,
        sheer: 0.15,
        coachRoof: false,
        coachRoofHeight: 0,
        coachRoofLength: 0,
        flybridge: false,
      },
      material: 'carbon',
      finish: 'satin',
    },
  },

  // --- WORKBOAT CATEGORY ---
  {
    id: 'fishing-trawler',
    name: 'Fishing Trawler',
    description: 'Working hull design with excellent stability and deck space. Built for all-weather operation.',
    category: 'workboat',
    icon: '🎣',
    unlockCost: 1500,
    performanceRating: {
      speed: 4,
      stability: 10,
      comfort: 5,
      efficiency: 6,
      seakeeping: 9,
    },
    config: {
      length: 12,
      beam: 4.5,
      draft: 1.2,
      freeboard: 1.1,
      bow: {
        type: 'spoon',
        angle: 35,
        overhang: 10,
        flare: 15,
        rake: 10,
        bulbSize: 0,
        bulbPosition: 0.5,
      },
      stern: {
        type: 'cruiser',
        angle: 20,
        overhang: 8,
        width: 0.95,
        height: 0.7,
        rake: 10,
      },
      keel: {
        type: 'round-bottom',
        depth: 0.6,
        length: 0.7,
        position: 0.5,
        sweep: 12,
        finType: 'stub',
        finDepth: 0.4,
      },
      chine: {
        type: 'hard',
        count: 1,
        positions: [0.35],
        angles: [10],
      },
      deck: {
        camber: 5,
        sheer: 0.3,
        coachRoof: true,
        coachRoofHeight: 0.9,
        coachRoofLength: 0.3,
        flybridge: true,
      },
      material: 'steel',
    },
  },

  // --- CLASSIC CATEGORY ---
  {
    id: 'classic-sloop',
    name: 'Classic Sloop',
    description: 'Traditional long-keel design with elegant lines. Timeless beauty and forgiving handling.',
    category: 'classic',
    icon: '🎻',
    unlockCost: 2500,
    performanceRating: {
      speed: 5,
      stability: 9,
      comfort: 7,
      efficiency: 6,
      seakeeping: 8,
    },
    config: {
      length: 13,
      beam: 3.8,
      draft: 1.5,
      freeboard: 0.9,
      bow: {
        type: 'clipper',
        angle: 28,
        overhang: 20,
        flare: 10,
        rake: 15,
        bulbSize: 0,
        bulbPosition: 0.5,
      },
      stern: {
        type: 'canoe',
        angle: 25,
        overhang: 18,
        width: 0.6,
        height: 0.65,
        rake: 18,
      },
      keel: {
        type: 'v-hull',
        depth: 0.8,
        length: 0.8,
        position: 0.5,
        sweep: 5,
        finType: 'fin',
        finDepth: 1.8,
      },
      chine: {
        type: 'none',
        count: 0,
        positions: [],
        angles: [],
      },
      rocker: {
        bowRise: 0.18,
        sternRise: 0.15,
        centerPoint: 0.5,
        continuous: true,
      },
      material: 'wood',
      finish: 'gloss',
      colors: {
        hull: '#8B4513',
        deck: '#DEB887',
        accent: '#D4A574',
        antifoul: '#2F1810',
      },
    },
  },
  {
    id: 'gaff-cutter',
    name: 'Gaff Cutter',
    description: 'Traditional gaff-rigged cutter hull. Deep forefoot and long keel for character sailing.',
    category: 'classic',
    icon: '⚓',
    unlockCost: 3000,
    performanceRating: {
      speed: 4,
      stability: 9,
      comfort: 7,
      efficiency: 5,
      seakeeping: 9,
    },
    config: {
      length: 11,
      beam: 3.5,
      draft: 1.4,
      freeboard: 0.8,
      bow: {
        type: 'spoon',
        angle: 32,
        overhang: 22,
        flare: 8,
        rake: 12,
        bulbSize: 0,
        bulbPosition: 0.5,
      },
      stern: {
        type: 'double-ended',
        angle: 28,
        overhang: 15,
        width: 0.45,
        height: 0.6,
        rake: 20,
      },
      keel: {
        type: 'round-bottom',
        depth: 1.0,
        length: 0.85,
        position: 0.5,
        sweep: 0,
        finType: 'none',
        finDepth: 0,
      },
      prismaticCoefficient: 0.52,
      blockCoefficient: 0.38,
      material: 'wood',
    },
  },
]

// Category icons and labels
export const HULL_CATEGORIES = {
  racing: { label: 'Racing', icon: '🏁', color: '#EF4444' },
  cruising: { label: 'Cruising', icon: '⛵', color: '#3B82F6' },
  expedition: { label: 'Expedition', icon: '🧭', color: '#10B981' },
  luxury: { label: 'Luxury', icon: '💎', color: '#8B5CF6' },
  workboat: { label: 'Workboat', icon: '🔧', color: '#F59E0B' },
  classic: { label: 'Classic', icon: '⚓', color: '#6366F1' },
} as const

// Get presets by category
export function getPresetsByCategory(category: HullPreset['category']): HullPreset[] {
  return HULL_PRESETS.filter(p => p.category === category)
}

// Get preset by ID
export function getPresetById(id: string): HullPreset | undefined {
  return HULL_PRESETS.find(p => p.id === id)
}

// Create a new config from preset
export function createConfigFromPreset(preset: HullPreset): ProceduralHullConfig {
  return {
    ...createDefaultConfig(),
    ...preset.config,
  }
}

// Export default config creator for use elsewhere
export { createDefaultConfig }
