export { KaleidoscopeCanvas, KaleidoscopeModal } from './KaleidoscopeCanvas'
export { BLADE_PRESETS, getPresetById, getPresetsByCategory, getUnlockedPresets } from './BladePresets'
export type { BladePreset } from './BladePresets'
export { interpolateSpline, applyKaleidoscope, normalizePoints, denormalizePoints } from './SplineUtils'
export { generateTurbineGeometry, generateBladeGeometry, generateHelixBlades } from './TurbineGenerator'
